Type hints; Slices in setitem/delitem; Type errors in rich comparisons
Details:

* Added Python type hints.

* Added support for passing slices to __setitem__() and __delitem__().
  Expanded the testcases accordingly.

* Fixed incorrect error handling when passing objects of unsupported types to
  the right hand operand of the rich comparison methods of NocaseList. This
  previously caused AttributeError "'list' object has no attribute 'lower'"
  and TypeError "'int' object is not iterable" to be raised which was confusing.
  This is now handled by returning 'NotImplemented' from these methods as
  recommended by Python, causing TypeError with a proper message to be raised
  by Python.
  Expanded the testcases accordingly.

Signed-off-by: Andreas Maier <andreas.r.maier@gmx.de>